// @ts-check

/**
 * @typedef {import("../generated/api").RunInput} RunInput
 * @typedef {import("../generated/api").FunctionRunResult} FunctionRunResult
 */

/**
 * @type {FunctionRunResult}
 */
const NO_CHANGES = {
	operations: [],
};

/**
 * @param {RunInput} input
 * @returns {FunctionRunResult}
 */
export function run(input) {
	// input is generated by the run.graphql schema when you hit the checkout
	// for testing purposes, go to the app page in partners > extensions > this extension and view the latest run details to get the input json
	// then save that to input.json in the extension folder, cd to the folder and run: cat input.json | npm run shopify app function run -- --export=run
	// this will show what the operations output will be without having to refresh the checkout
	let operations = [];
	input.cart.lines.map((line) => {
		// @ts-ignore
		let newTitle = line.merchandise.product.title.replaceAll(" ", " / ");
		operations.push({
			update: {
				cartLineId: line.id,
				title: newTitle,
			},
		});
	});
	return {
		operations: operations,
	};
}
